version: '3.1'

services:
  httpserver:
    build:
      context: https://github.com/k6mil6/gpt4free.git
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
  migrator:
    build:
      context: .
      dockerfile: migrator.Dockerfile
    depends_on:
      - db
  bot:
    build:
      context: .
      dockerfile: bot.Dockerfile
    depends_on:
      - db
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: news_feed_bot
      PGDATA: /var/lib/postgresql/data/
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data/

volumes:
  db: