version: '3.1'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "5430:5432"
    networks:
      net:
        ipv4_address: 192.167.240.2
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: news_feed_bot
      PGDATA: /var/lib/postgresql/data/
    ports:
      - "5431:5432"
    volumes:
      - db:/var/lib/postgresql/data/
    networks:
      net:
        ipv4_address: 192.167.240.3
networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.167.240.0/24

volumes:
  db: